<script>
  import FaqAccordion from '../Faq.svelte';

  const faqs = [
    {
      question: "Should we build Native (Swift/Kotlin) or Cross-Platform (React Native/Flutter)?",
      description: "If your app is primarily fetching database arrays and displaying them (like an e-commerce or SaaS app), Cross-Platform is strictly superior: it halves the code maintenance cost. If your app relies heavily on C++ rendering, ARKit, or precise audio synchronization, Native is non-negotiable."
    },
    {
      question: "How do you handle backend hosting for mobile?",
      description: "We utilize highly redundant serverless architecture via Firebase or AWS Amplify to manage auth tokens, push notification fan-outs, and rapid database scaling without hiring dedicated DevOps."
    },
    {
      question: "Can you take over an existing crashing codebase?",
      description: "Yes, but with caveats. We will run an initial paid diagnostic sprint to assess the toxicity generated by the previous agency. If the existing monolithic code cannot be salvaged reasonably, we will pitch a phased rewrite."
    },
    {
      question: "Do you integrate third-party analytics natively?",
      description: "Absolutely. We wrap APIs for Amplitude, Posthog, and Firebase into a custom TypeScript/Dart analytics manager class. We log precise tap events, user drop-offs, and critical exceptions back to your dashboard."
    }
  ];
</script>

<section class="bg-slate-50 py-24 border-t border-slate-100">
  <div class="container mx-auto px-6 max-w-7xl">
    <div class="flex flex-col lg:flex-row gap-16">
      
      <div class="lg:w-1/3">
        <h2 class="text-xs font-bold uppercase tracking-[0.2em] text-[#00c6ff] mb-4">Questions Answered</h2>
        <h3 class="text-4xl lg:text-5xl font-black text-[#1f4e79] tracking-tight mb-6">Technical Scope</h3>
        <p class="text-slate-600 leading-relaxed max-w-md">Detailed context covering platform decisions, third-party library integrations, and rescue operations.</p>
      </div>

      <div class="lg:w-2/3">
        <FaqAccordion items={faqs} />
      </div>

    </div>
  </div>
</section>
